package com.mysql.db;

/* *
 *  This program, with required dependencies, 
 * has been generated by Spring Initializr.
 * It enables persistence of data in MySQL Workbench
 * using Java Persistence API.
 * It can be tested in Postman software
 * from where data can also be sent to MySQL Workbench.
 * */

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

@EnableJpaRepositories(basePackages = "com.mysql.db.dao")
@SpringBootApplication
public class SpringBootMySqlApplication {

	public static void main(String[] args) {
		SpringApplication.run(SpringBootMySqlApplication.class, args);
	}

}
